apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-express
  labels:
    app: simple-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-express
  template:
    metadata:
      labels:
        app: simple-express
    spec:
      containers:
      - name: simple-express
        image: tebohoxthapeli/simple-express:latest
        ports:
        - containerPort: 8080
